### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by dennis777** [paulbtw/mcbrokenio#22]
Hello! Came across this project completely by chance and love it! I would like to expand on it but was wondering how you got the API keys? Do you always use the Australian endpoint to get the API token then use the proper regional one to make the requests? Also you mentioned something about getting the basic token from the McDonald's App to then send a request to get the API token. How do you get to that? What are the necessary headers required to send these API requests? Thanks!

**Comment by dennis777** [comment]
In other words how do I get the Authorization Bearer Token (which will need to be refreshed every 15 minutes)

**Comment by paulbtw** [comment]
Hi, sorry for responding so late.
I used charles proxy to read the request and responses from the apps on my phone.
Then you can open the app on your phone and see all requests done by it, including the `https://ap-prod.api.mcd.com/v1/security/auth/token` request. In there you can see your basic token, this token will not expire, and you can use it to get the bearer tokens.

**Comment by dennis777** [comment]
Sorry I forgot to close this request. I ended up figuring it out myself. The issue was my McDonalds app (at least on iOS) was not making any `https://ap-prod.api.mcd.com/v1/security/auth/token` calls only a call to refresh the existing token `https://us-prod.api.mcd.com/exp/v1/customer/login/refresh`
 > *(which is extremely fragile i.e. once you call it you cant call it again unless you call it with updated token but if you lose track of that current token or your current token expires you cant make the call which defeats the whole purpose)*

I ended up just brute forcing some logical calls to the `https://ap-prod.api.mcd.com/v1/security/auth/token` endpoint and basically discovered it that way. For anyone else interested, you will need 2 keys/mini tokens from the mcd app one is called `mcd-clientid` and `mcd-clientsecret`. 

Your Basic token is just `mcd-clientid:mcd-clientsecret` base64 encoded. You then sent a POST request to that api location with Basic Auth and `content-type: application/x-www-form-urlencoded` in the headers and that's it. You'll get a token in the response as well as when it expires (It's valid for 900sec or 15min, I've never seen it change)


So for example if my clientid is mdconalds and clientsecret is bigmacs then my API call would look like:
> *Example using REST*
```
POST /v1/security/auth/token HTTP/1.1
Authorization: Basic bWNkb25hbGRzOmJpZ21hY3M=
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
host: us-prod.api.mcd.com
Content-Length: 0
```

**Comment by dennis777** [comment]
But now that I know you're still active I wanted to ask 2 things. Firstly the simpler question how did you get the list of all stores? When I make the call to get nearby locations I get back a maximum of 30 stores? Did you just scrape around until you got all of them into a list? See below
> API Call to `https://us-prod.api.mcd.com/exp/v1/restaurant/location?distance=10000000&filter=summary&pageSize=250&latitude=38.65&longitude=-121.28`
> <img width="393" alt="image" src="https://github.com/paulbtw/mcbrokenio/assets/25965937/306cfbb7-2165-4914-99b7-61e04a329b4f">
> As you can see I only get 30 restaurants back in the response

Secondly, how did you deal with rate limits? You're making calls to get the products (check availability) but I also make calls to the store catalog `https://us-prod.api.mcd.com/exp/v1/menu/catalog/US/19976?filter=summary` in order to get the prices and be able to compare prices of same items between stores. Even with a 1000ms delay (which is really slow and excessive) the catalog call and even products call will eventually timeout. 

I've been thinking I cant have these calls be made on device and possibly need a server to update all these locations slowly every second but that poses challenges within itself because of how slow these updates happen. I would have restarurants with data that hasn't been updated for 10+ hours. Thus id prefer to keep it all on device.

So how do you a) get all the locations in US, b) Deal with rate limits? Thank you for your time I appreciate it :)

**Comment by paulbtw** [comment]
First questions:
When I started the project, you could request up to 1000 nearby stores. They changed it at some point. I first didn't notices the change, as the database had all stores already. To fix this I just generate a [coordinates mesh](https://github.com/paulbtw/mcbrokenio/blob/master/src/libs/utils/generateCoordinatesMesh.ts) with the min/max lat + lng of a mcdonalds location. This still has problems with the US for example, as they are to big. Because I was lazy I just split the US in 4 equal parts so the lambda won't time out. I also noticed that different mcdonalds apis have different range for finding stores nearby, so the distance I use might not be perfect.

Second:
At the start of the project, the rate limit was way higher than now and they didn't restricte the api's by api (You can't access the US API from Germany, same for nearly every other API). Should be around 5 requests/sec at the moment. For that, I implemented a really simple [queue system ](https://github.com/paulbtw/mcbrokenio/blob/d336cbcfd8cd267299e47a2de5391594215068d2/src/libs/services/getItemStatus/index.ts#L22) to limit the requests made per second. This is again different in each McDonald's API location, that's why the limit is variable inside the function. You can check them out [here](https://github.com/paulbtw/mcbrokenio/blob/master/src/libs/constants/RateLimit.ts). They could be different now. I just trial and errored. Sometimes the API is slow.

**Comment by dennis777** [comment]
Gotcha okay. Makes sense I figured I would need to make some sort of mesh but was curious if I was simply misusing the API

For the rate limits I guess the `https://us-prod.api.mcd.com/exp/v1/restaurant/STOREID?filter=full&storeUniqueIdType=NatlStrNumber` call is limited to around 5 req/sec but the `https://us-prod.api.mcd.com/exp/v1/menu/catalog/US/STOREID?filter=summary` is even more heavily limited (which is the endpoint I need to get the prices of products) 


Anyway your help was much appreciated thank you!

**Comment by dennis777** [comment]
Do you think you can post a list of all the nationalStoreIds?

I would want to make sure I'm not missing any 😅 this catalog endpoint is so fragile you're lucky you aren't dealing with it

**Comment by paulbtw** [comment]
Hi, sure I can upload that. Let's hope I have every store. There are currently 20891 stores in the list
Check the attachted csv
[Pos.csv](https://github.com/user-attachments/files/16168319/Pos.csv)

**Comment by dennis777** [comment]
Thank you!
